baseURL = 'https://ep2p.github.io/kademlia-api/'
languageCode = 'en-us'
title = 'EP2P | Kademlia API'
disableKinds = ['taxonomy', 'taxonomyTerm']

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
    BookTheme = 'auto'
    BookToC = true
    BookMenuBundle = "/menu"
